on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  BASELINE: base
  IAI_CALLGRIND_RUNNER: iai-callgrind-runner

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: bench
jobs:
  iai:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Valgrind
        run: sudo apt update && sudo apt install valgrind && sudo apt-get install tree
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall
      - name: Install iai-callgrind-runner
        run: |
          echo "::group::Install"
          cargo binstall iai-callgrind-runner --no-confirm --no-symlinks --force
          echo "::endgroup::"
          echo "::group::Verification"
          which iai-callgrind-runner
          echo "::endgroup::"
      - name: Checkout base
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref || 'main' }}
      - name: Save baseline
        run: cargo bench --bench play_game -- --save-baseline=$BASELINE
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Compare PR benchmarks
        run: cargo bench --bench play_game -- --baseline=$BASELINE

      - name: Tree
        run: tree

      - name: Archive Performance Data
        uses: actions/upload-artifact@v4
        with:
          name: performance-data
          path: |
            target/iai/iai_test/play_game/play_game_group/bench_play_game/*.svg

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: $${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifactUrl = `https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts`
            const prNumber = context.payload.pull_request.number;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `![Artifact](https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts) \nArtifact URL: [Download SVG](https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts)`
            })
