on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  BASELINE: base
  IAI_CALLGRIND_RUNNER: iai-callgrind-runner

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: bench
jobs:
  iai:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      deployments: read
      packages: none
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Valgrind
        run: sudo apt update && sudo apt install valgrind && sudo apt-get install tree
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall
      - name: Install iai-callgrind-runner
        run: |
          echo "::group::Install"
          cargo binstall iai-callgrind-runner --no-confirm --no-symlinks --force
          echo "::endgroup::"
          echo "::group::Verification"
          which iai-callgrind-runner
          echo "::endgroup::"
      - name: Checkout base
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref || 'main' }}
      - name: Save baseline
        run: cargo bench --bench play_game -- --save-baseline=$BASELINE
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Compare PR benchmarks
        run: |
          # EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          cargo --color never bench --bench play_game -- --baseline=$BASELINE # > bla.txt
          # echo "speedup<<$EOF" >> $GITHUB_OUTPUT
          # cat bla.txt >> $GITHUB_OUTPUT
          #echo "$EOF" >> $GITHUB_OUTPUT
        id: comparison

      - name: Tree
        run: tree

      - name: Archive Performance Data
        uses: actions/upload-artifact@v4
        with:
          name: performance-data
          path: |
            target/iai/iai_test/play_game/play_game_group/bench_play_game/callgrind.bench_play_game.flamegraph.Ir.diff.base@base.svg

      - name: Convert SVG to Base64
        id: convert
        run: |
          # Convert the SVG to Base64 and save to an environment variable
          base64_encoded=$(base64 -w 0 target/iai/iai_test/play_game/play_game_group/bench_play_game/callgrind.bench_play_game.flamegraph.Ir.diff.base@base.svg)
          echo "BASE64_SVG=${base64_encoded}"
          echo "BASE64_SVG=${base64_encoded}" >> $GITHUB_ENV

      - name: Delete all previous comments by workflow
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number, 
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log(context)
            console.log(github)
            // Iterate over all comments and delete each one
            for (const comment of comments) {
              console.log(comment)
              if (comment.user.login === 'github-actions[bot]') { // Only delete comments made by the workflow bot
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                });
              }
            }
        
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const base64Svg = process.env.BENCH_DIFF;
            const body = `$${{ steps.comparison.outputs.speedup }}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })
